version: "3.4"

networks:
 kong-net:
  driver: bridge

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-db:
    image: postgres:latest
    restart: always
    networks:
      - kong-net
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    build: .
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    env_file:
      - .env
    links:
      - kong-db
    depends_on:
      - kong-db

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    build: .
    restart: always
    networks:
      - kong-net
    env_file:
      - .env
    environment:
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
      - kong-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"